/**
 * Recipe App OpenAPI Specification
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface IngredientDto {
  /**
   * Automatically generated id, unique
   */
  id: number;
  /**
   * Name of the ingredient
   */
  name: string;
}
